function [XCMP,cfsCMP,dimCFS] = func_compress_dw2d(X)
% FUNC_COMPRESS_DW2D Saved Compression Process.
%   X: matrix of data
%   -----------------
%   XCMP: matrix of compressed data
%   cfsCMP: decomposition vector (see WAVEDEC2)
%   dimCFS: corresponding bookkeeping matrix

%  Auto-generated by Wavelet Toolbox on 01-May-2016 14:12:16

% Analysis parameters.
%---------------------
wname = 'bior6.8';
level = 7;

% Compression parameters.
%------------------------
% meth = 'bal_sn';
sorh = 'h';    % Specified soft or hard thresholding
thrSettings = 27.873905406858860;
roundFLAG = true;

% Compression using WDENCMP.
%--------------------------
[coefs,sizes] = wavedec2(X,level,wname);
[XCMP,cfsCMP,dimCFS] = wdencmp('gbl',coefs,sizes, ...
    wname,level,thrSettings,sorh,1);
if roundFLAG , XCMP = round(XCMP); end
if isequal(class(X),'uint8') , XCMP = uint8(XCMP); end
